### ISSUE TITLE
async function Unexpected token function

### ISSUE THREAD

**Issue by qihan1994** [rook2pawn/node-ddos#19]
I am using Node v7.2.0 with { "ddos": "^0.1.16" }.

Running into this problem
```
.../node_modules/ddos/index.js:111
ddos.prototype.koa = async function (ctx, next) {
                           ^^^^^^^^
SyntaxError: Unexpected token function
    at Object.exports.runInThisContext (vm.js:78:16)
    at Module._compile (module.js:543:28)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
...
```

**Comment by rook2pawn** [comment]
@qihan1994 ah, sorry about that! Koa switched their function signatures. At one point they accepted promises which i would have used but it seems they really want you to use the async / await functions in node 7.6+. 

Ill make it not load until runtime for koa for the next release. IN the meantime, let me know if you can switch to node 7.6+

**Comment by rook2pawn** [comment]
@qihan1994 fixed https://github.com/rook2pawn/node-ddos/commit/c5ea0158877c64bf6aeb8b78fe2b72e849ca82e7

Now runs for pre 7.6 and post 7.6 node.

**Comment by qihan1994** [comment]
thanks!
