### ISSUE TITLE
Unexpected token *

### ISSUE THREAD

**Issue by jeanguybillard** [rook2pawn/node-ddos#7]
After installing ddos onto my express project by following the node-ddos installation procedure, i am getting an Unexpected token * cause 

Error stack
```
/var/www/vhosts/project/node_modules/ddos/index.js:83
    this.koa = function *(next) {
                        ^
SyntaxError: Unexpected token *
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/var/www/vhosts/project/app.js:15:12)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```
Please inform me how to fix this issue. 
Best Regards,

**Comment by jeanguybillard** [comment]
Upgraded to v4.0.x and it works
